apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: kasiapetka/kub-data-demo:latest
          env:
            - name: STORY_FOLDER
              # value: 'story'
              #If we want to use config maps: 
              valueFrom: 
                configMapKeyRef: 
                  name: data-store-env
                  key: folder
          imagePullPolicy: Always
          volumeMounts: 
          # path in the contianer where the empty directory should be mounted
            - mountPath: /app/story
              name: story-volume
      volumes:
        - name: story-volume
          persistentVolumeClaim: 
            claimName: host-pvc

        # empty dir creates an empty directory whenever the pod starts and it keeps it alive as 
        # long as the pod is not destroyed

        # emptyDir: {}

        # allows us to set a path on the host machine, so on the node, 
        # and then the data from that path will be exposed to the different pods

        # hostPath:
        #   path: /data
        # the path type says if it should be a directory and if it does not exist, create it
        #   type: DirectoryOrCreate


