version: '3.8'

services:
  server:
    platform: linux/x86_64
    build: 
      # we need to sepcify a . here, as in dockerfile we use nginx and src folders which are outside of dockerfiles folder
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports:
      - '8000:80'
    # bind mounts for development    
    # volumes:
      # - ./src:/var/www/html
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql

  php:
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    # bind mounts for development  
    # volumes:
      # - ./src:/var/www/html:delegated
      # delegated means that it will be refreshed in batches - better performance

  mysql:
    platform: linux/x86_64
    image: 'mysql:5.7'
    env_file:
      - ./env/mysql.env

  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
 
  artisan:
    build: 
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ./src:/var/www/html
    # if we want to override or add entrypoint to a dockerfile we can use it like:
    entrypoint: ["php", "/var/www/html/artisan"]
    
  npm:
    image: 'node:14'
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html