#persistent volumes not go with type host Path -> it is only for testing here and would not work on a multi node cluster
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  # there are two available modes, Filesystem and Block - different sotrage types
  # block storage is at its best when providing access to blocks that form part of larger files
  # file storage is good for storing and accessing files. 
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce 
  hostPath:
    path: /data
    type: DirectoryOrCreate
