apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: 
    group: example
spec: 
  selector:
    # service selectro has only matchLabels identifier, therefore it does not need to be specified here
    app: jsapp
  ports:
    - protocol: 'TCP'
      port: 80 #this is a port exposed to the outside
      targetPort: 8080 #this is the port in the container
    # - protocol: 'TCP'
    #   port: 443 
    #   targetPort: 443 
  type: 'LoadBalancer'
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: js-app
  labels:
    group: example
spec: 
  replicas: 2
  # selector is mandatory, matchLabels key helps the 
  # deployment to select the pods it needs to control when it is running after we applied the file
  # only pods with both those labels will be controlled by this deployment
  selector: 
    # matchExpressions:
    matchLabels:
      app: jsapp
      tier: backend
  template:
  # it is always a pod template for deployment, we dont need a kind: Pod here
    metadata: 
      labels: 
        app: jsapp
        tier: backend
    spec:
      containers: 
        - name: node-js-app
          image: kasiapetka/kub-app:1
        #   for multiple containers:
        # - name: ...
        #   image: ...
