apiVersion: v1
kind: Service
metadata:
  name: backend
spec: 
  selector:
    # service selectro has only matchLabels identifier, therefore it does not need to be specified here
    app: jsapp
  ports:
    - protocol: 'TCP'
      port: 80 #this is a port exposed to the outside
      targetPort: 8080 #this is the port in the container
    # - protocol: 'TCP'
    #   port: 443 
    #   targetPort: 443 
  type: 'LoadBalancer'