apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels: 
        app: api-auth
    spec:
      containers:
        - name: auth-api-app
          image: kasiapetka/kub-demo-auth:latest
