apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tasks-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-tasks
  template:
    metadata:
      labels:
        app: api-tasks
    spec:
      containers:
        - name: tasks-api-app
          image: kasiapetka/kub-demo-tasks:latest
          env:
            - name: AUTH_URL
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks

