apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deploy
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: api-users
  template:
    metadata:
      labels:
        app: api-users
    spec:
      containers:
        - name: users-api-app
          image: kasiapetka/kub-demo-users:latest      
          env:
            - name: AUTH_URL
              value: "auth-service.default"
              # value: "10.103.102.237"

        # to have another container in the pod, we need just to add another object here: 
        # - name: auth-api-app
        #   image: kasiapetka/kub-demo-auth:latest
         
